### PR TITLE
Adding Xbb tagger.

### PR DESCRIPTION
**Pull request by kratsg**

### CODE REVIEW

**Comment by kratsg** [comment]
Initial merge now. No tool has been made yet until this is nailed down.

**Comment by mileswu** [comment]
Does this compile in AthAnalysisBase too?

**Comment by kratsg** [comment]
Yeah, I had no issues with AthAnalysisBase. I just grabbed a version and checked that. But I'd rather wait until I hear from Reina about the config file -- I guess by Wednesday?

**Comment by mileswu** [comment]
OK sounds good

**Pull request merged**
